server:
  port: 8088
spring:
  application:
    name: springboot_mybatis_plus
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: 123456
logging:
  level:
    root: info
    com.fastdevelop.spring_boot_mybatis_plus: info